export const crossoverData: { [key: string]: string[] } = {
  "Abalos, Ramiro": ["Albatros"],
  "Abdala, Juan Jose": ["Larranaga"],
  "Abella, Diego": ["Goes"],
  "Abirad, Alvaro": ["Auriblanco", "Waston"],
  "Abraham, David": ["Hebraica Macabi", "Plaza De Nueva Helvecia"],
  "Abratanski, Gabriel": ["Aguada", "Cader", "Circulo Sportivo", "Goes", "Hebraica Macabi", "Nacional De Fraybentos", "Praga", "Salto Uruguay", "Trouviille", "Union Atletica", "Verdirrojo", "Welcome"],
  "Abratanski, Sergio": ["Welcome", "Yale"],
  "Acevedo, Yari": ["Larre Borges", "Miramar"],
  "Acosta, Agustin": ["Cader", "Cordon", "San Telmo", "Tabare"],
  "Acosta, Alejandro": ["Goes", "Nacional", "Trouviille", "Waston", "Welcome"],
  "Acosta, Camilo": ["Bigua", "Cordon", "Larre Borges", "Malvin"],
  "Acosta, Diego": ["Independiente", "Nacional De Fraybentos", "Soriano"],
  "Acosta, Luis": ["Stockolmo"],
  "Acuna, Diego": ["Reducto"],
  "Acuna, Milton": ["25 De Agosto", "Ateneo", "Cader", "Larre Borges", "Olivol Mundial", "San Telmo", "Sayago", "Yale"],
  "Acuna, Pablo": ["Olimpia"],
  "Acuna, Ramiro": ["25 De Agosto", "Atenas", "Ateneo", "Bohemios", "Circulo Sportivo", "Independiente", "Marne", "Nacional De Fraybentos", "Olimpia", "Sayago", "Tabare", "Trouviille"],
  "Adorian, Ivan": ["Tabare"],
  "Agarbado, Abel": ["Olimpia"],
  "Agarbado, Efrain": ["25 De Agosto", "Olimpia", "Stockolmo", "Verdirrojo"],
  "Aguiar, Diego": ["Verdirrojo"],
  "Aguilar, Hector": ["Atenas"],
  "Aguilera, Martin": ["25 De Agosto", "Anastasia", "Trouviille"],
  "Baamonde, Ricardo": ["Welcome"],
  "Balbi, William": ["Goes", "Malvin", "San Telmo", "Waston"],
  "Balbuena, Gonzalo": ["Larranaga", "Union Atletica", "Welcome"],
  "Ballejos, Carlos": ["Union Atletica"],
  "Ballejos, Lus": ["Miramar"],
  "Baltasar, Federico": ["Colon", "Malvin"],
  "Banquerque, Sebastin": ["Aguada", "Anastasia", "Urunday Universitario"],
  "Barcelona, Luis": ["25 De Agosto", "Bohemios", "Juventud", "Nacional", "San Telmo", "Yale"],
  "Barrera, Bernardo": ["25 De Agosto", "Bohemios", "Welcome"],
  "Barrera, Gustavo": ["Atenas", "Hebraica Macabi"],
  "Barreto, Gustavo": ["Larranaga"],
  "Barreto, Javier": ["25 De Agosto", "Sayago"],
  "Barriola, Miguel": ["Aguada", "Anastasia", "Atenas", "Hebraica Macabi", "Trouviille", "Waston", "Welcome"],
  "Barrios, Gabriel": ["Urunday Universitario"],
  "Barrios, Matas": ["Urunday Universitario"],
  "Barses, Federico": ["25 De Agosto"],
  "Bascou , Claudio": ["Olivol Mundial", "Trouviille"],
  "Bassi, Sebastin": ["Verdirrojo"],
  "Bastn Emiliano": ["Atenas", "Bigua", "Montevideo", "Trouviille", "Verdirrojo", "Waston", "Welcome"],
  "Batista, Esteban": ["Nacional"],
  "Baudine, Fernando": ["Goes", "Stockolmo", "Verdirrojo"],
  "Benelli, Marcelo": ["Larranaga", "Marne", "Olivol Mundial", "Waston", "Welcome"],
  "Bentez, Andres": ["Larranaga"],
  "Bentez, Matas": ["Colon", "Tabare"],
  "Bentez, Mauricio": ["Auriblanco"],
  "Berta, Javier": ["Defensor Sporting"],
  "Bertolini, Adrin": ["Aguada", "Cader", "Cordon", "Hebraica Macabi", "Montevideo", "Nacional", "Racing", "Salto Uruguay", "Union Atletica"],
  "Bertolotti, Emiliano": ["Yale"],
  "Bertoni, Valerio": ["Anastasia", "Nacional", "Praga"],
  "Bica, Richard": ["Miramar"],
  "Blanco, Andrs": ["Verdirrojo"],
  "Blankson, Ryan": ["Cordon", "Nacional", "Tabare"],
  "Bo, Maximiliano": ["Montevideo", "Yale"],
  "Bonda, Javier": ["Cordon", "Defensor Sporting"],
  "Bonello, Gonzalo": ["Independiente", "Miramar"],
  "Borges, Alexander": ["Cordon"],
  "Borges, Ignacio": ["Atenas", "Cordon", "Ferro Carril", "Paysandu", "Remeros", "Trouviille"],
  "Borroni, Andrs": ["Goes", "Larranaga", "Olimpia", "Verdirrojo"],
  "Borsani, Aurelio": ["25 De Agosto", "Larre Borges", "Sayago", "Union Atletica", "Welcome"],
  "Borsellino, Nicols": ["Malvin", "Urunday Universitario"],
  "Borteiro, Sebastian": ["Verdirrojo"],
  "Boscardin, Fabin": ["Aguada"],
  "Botali, Federico": ["Sayago"],
  "Botta, Maximiliano": ["Bigua", "Cader", "Colon", "Yale"],
  "Bouchatn, Leonardo": ["Hebraica Macabi", "Larre Borges", "Stockolmo"],
  "Brea Gonzalo": ["Atenas"],
  "Bruni, Guillermo": ["Larre Borges", "Trouviille"],
  "Bruno, Facundo": ["Larranaga", "Malvin"],
  "Buffa, Paulo": ["Sayago"],
  "Burgueo, Santiago": ["Lagomar"],
  "Busanello, Ignacio": ["Larranaga"],
  "CICHEVSKI, Alejandro": ["Union Atletica"],
  "Caballero, Ramiro": ["Auriblanco", "Urupan", "Verdirrojo"],
  "Cabot, Marcos": ["Defensor Sporting", "Trouviille"],
  "Cabral, Fernando": ["Aguada", "Ateneo", "Independiente", "Yale"],
  "Cabrera, Francisco": ["Malvin", "Touring", "Welcome"],
  "Cabrera, Jorge": ["Aguada"],
  "Caceres, Hernando": ["Anastasia", "Goes", "Trouviille"],
  "Cadenasso, Alejandro": ["Anastasia", "Larre Borges", "Paysandu", "Salto Uruguay", "Touring"],
  "Calfani, Matias": ["Bigua", "Malvin", "Tabare"],
  "Calone, Nicolas": ["Verdirrojo"],
  "Cambon, Ignacio": ["Atenas", "Bigua", "Guruyu Waston", "Nacional", "Union Atletica"],
  "Camejo, Felipe": ["Larranaga"],
  "Campana, Eduardo": ["Larranaga"],
  "Campora, Federico": ["Aguada", "Atenas", "Cordon", "Ferro Carril", "Malvin", "Sayago", "Trouviille"],
  "Canepa, Juan Pablo": ["Aguada"],
  "Cano, Juan": ["Union Atletica"],
  "Cano, Sebastian": ["Bohemios"],
  "Capalbo, Lucas": ["Malvin"],
  "Caputi, Mateo": ["Larranaga", "Nacional"],
  "Carbajal, Nicolas": ["Olimpia"],
  "Carballo, Matias0": ["Olimpia"],
  "Cardoney, Rodrigo": ["Miramar", "Stockolmo"],
  "Cardozo Grudnicki, Rodrigo": ["Lagomar"],
  "Cardozo, Victor": ["Goes"],
  "Carrabs, Fabricio": ["Defensor Sporting", "Romis Nelimar"],
  "Carranza, Joaquin": ["Cader"],
  "Carrerou, Andres": ["Bohemios"],
  "Carrerou, Ignacio": ["Atenas", "Bohemios"],
  "Carril, Rodrigo": ["Atenas", "Auriblanco"],
  "Carro, Fabian": ["Larre Borges", "Las Bovedas", "San Telmo"],
  "Caruso, Diego": ["Marne", "Nacional"],
  "Carvalho, Gabriel": ["Tabare"],
  "Carvidon, Gonzalo": ["Bigua", "Nacional"],
  "Carvidon, Rodrigo": ["Aguada", "Bigua", "Cader", "Urunday Universitario", "Welcome"],
  "Casalas, Diego": ["Colon", "Plaza De Nueva Helvecia", "Romis Nelimar"],
  "Castagnaro, Sebastian": ["Salto Uruguay"],
  "Castell, Carlos": ["25 De Agosto", "Colon", "Independiente", "Malvin", "Marne", "Nacional", "Stockolmo", "Urunday Universitario", "Waston"],
  "Castello, Sergio": ["Nacional", "Reducto"],
  "Castillo, Facundo": ["Urunday Universitario"],
  "Castineira, Gonzalo": ["Larre Borges", "Union Atletica"],
  "Castro, Favio": ["25 De Agosto", "Union Atletica"],
  "Castro, Ignacio": ["Aguada"],
  "Castro, Joaquin": ["Goes"],
  "Castro, Martin": ["Defensor Sporting", "Independiente"],
  "Castro, Rodrigo": ["Bigua", "Defensor Sporting"],
  "Castro, Santiago": ["Miramar"],
  "Castro, Sebastian": ["Larranaga", "Sayago"],
  "Catala, Nicolas": ["Anastasia", "Atenas", "Bohemios", "Marne", "Olivol Mundial", "Trouviille", "Yale"],
  "Cavalli, Gaston": ["Defensor Sporting", "Guruyu Waston", "Nacional", "Olivol Mundial", "Sayago", "Stockolmo", "Union Atletica"],
  "Cawen, Joaquin": ["Cordon"],
  "Cervi, Maximiliano": ["Atenas", "Cordon", "Malvin", "Olimpia", "Praga", "Verdirrojo"],
  "Cervieri, Diego": ["Circulo Sportivo", "Nacional", "Salto Uruguay"],
  "Chamorro, Pablo": ["Albatros", "Larranaga", "Miramar", "Stockolmo"],
  "Charquero, Claudio": ["Aguada", "Cordon", "Goes", "Larre Borges", "Nacional", "Paysandu", "Praga", "Tabare", "Trouviille", "Union Atletica", "Welcome", "Yale"],
  "Chevalier, Eduardo": ["Cordon"],
  "Chimanoski, Alvin": ["Albatros"],
  "Chiriazis, Jorge": ["Juventud"],
  "Chittadini, Sebastian": ["Larranaga", "Miramar", "Reducto", "Urupan"],
  "Cieslinkas, Christian": ["Union Atletica"],
  "Cieslinkas, Nicolas": ["Union Atletica"],
  "Clerici, Pablo": ["Atenas", "Independiente", "Marne", "Montevideo", "Olimpia", "Union Atletica", "Welcome"],
  "Cocchi, Franco": ["25 De Agosto"],
  "Coelho, Lorenzo": ["Defensor Sporting"],
  "Coelho, Rodrigo": ["Malvin"],
  "Coito, Juan Martin": ["Urunday Universitario"],
  "Colman, Camilo": ["Auriblanco", "Colon", "Larranaga", "Miramar"],
  "Colman, Richard": ["Atenas", "Auriblanco", "Paysandu", "Yale"],
  "Colombo, Angelo": ["Cordon"],
  "Comas, Nicolas": ["Defensor Sporting"],
  "Compan, Raul": ["Nacional"],
  "Confalonieri, Alejandro": ["Atenas"],
  "Coronado, Juan": ["Olimpia"],
  "Correa, Matias": ["Defensor Sporting", "Independiente", "Nacional", "Racing", "Remeros", "Verdirrojo"],
  "Correa, Mauricio": ["Larre Borges", "Las Bovedas"],
  "Correa, Maximiliano": ["Atenas", "Yale"],
  "Corsino, Nicolas": ["Larranaga", "Miramar"],
  "Cortes, Geronimo": ["Albatros"],
  "Corti, Nicolas": ["Bohemios"],
  "Cortiza, German": ["Aguada", "Olivol Mundial"],
  "Coselino, Santiago": ["Stockolmo"],
  "Couto, Agustin": ["Juventud", "Malvin", "Olivol Mundial", "Praga"],
  "Couto, Juan": ["Tabare"],
  "Craig, Brian": ["Aguada", "Bohemios", "Paysandu", "Tabare", "Urunday Universitario", "Waston"],
  "Crespi, Francisco": ["Malvin"],
  "Cresseri, Andres": ["Larranaga"],
  "Crocano, Javier": ["25 De Agosto", "Anastasia", "Cader", "Cordon", "Larre Borges", "Malvin", "Marne", "Praga", "Stockolmo", "Urunday Universitario", "Verdirrojo"],
  "Cuna, Gaston": ["Defensor Sporting", "Goes", "Larre Borges"],
  "Cuneo, Conrado": ["Anastasia"],
  "Curadossi, Bruno": ["Nacional"],
  "Curbelo, Facundo": ["Juventud"],
  "Curbelo, Federico": ["Auriblanco", "Marne", "Miramar", "Nacional", "Waston"],
  "Curbelo, Guillermo": ["Trouviille"],
  "Da Costa, Agustin": ["Bohemios"],
  "Da Nobrega (Magrao), Carlos": ["Aguada", "Colon", "Cordon", "Plaza"],
  "Da Rosa, Santiago": ["Aguada", "Lagomar", "Nacional", "Plaza"],
  "Da Silva, Hakeem": ["Atenas"],
  "Danglada, Esteban": ["Auriblanco", "Verdirrojo"],
  "De Armas, Rodrigo": ["Aguada", "Albatros", "Colon", "Las Bovedas", "Tabare", "Trouviille", "Yale"],
  "De Avila, Ronald": ["Atenas", "Olivol Mundial"],
  "De Fino, Maximiliano": ["Cader", "Nacional"],
  "De Gouveia, Matias": ["Atenas", "Goes", "Montevideo", "Tabare", "Union Atletica", "Welcome"],
  "De Leon, Ignacio": ["Juventud", "Marne", "Stockolmo"],
  "De Leon, Luis": ["Atenas", "Larranaga", "Nacional", "Nacional De Fraybentos", "Olimpia", "Paysandu", "Stockolmo", "Verdirrojo", "Yale"],
  "De Leon, Rogelio": ["Aguada", "Cader", "Marne", "Romis Nelimar", "Sayago", "Stockolmo", "Trouviille", "Urunday Universitario", "Verdirrojo", "Yale"],
  "De Los Santos, Brian": ["Goes"],
  "De Los Santos, Gaston": ["Ferro Carril"],
  "De Melo, Juan": ["Yale"],
  "De Pena, Jorge": ["Aguada", "Circulo Sportivo", "Hebraica Macabi", "Olimpia", "Sayago", "Waston", "Yale"],
  "De Pena, Leonardo": ["Marne", "Miramar", "Sayago"],
  "De Rosa, Roque": ["Independiente"],
  "De Souza, Nicolas": ["Anastasia"],
  "De las Nieves, Lucas": ["Larre Borges", "Stockolmo", "Yale"],
  "De los Santos, Gabriel": ["Defensor Sporting"],
  "Dean, Esteban": ["Defensor Sporting", "San Telmo"],
  "Del Puerto, Ernesto": ["Goes", "Sayago", "Stockolmo"],
  "Del, Federico": ["Goes", "Union Atletica"],
  "Delfino, Agustin": ["Montevideo"],
  "Delfino, Andres": ["Reducto"],
  "Delfino, Danilo": ["Lagomar", "Union Atletica"],
  "Delgado, Juan": ["Atenas", "Ateneo", "Juventud", "Marne", "Olivol Mundial", "Welcome"],
  "Delgado, Nicolas": ["Defensor Sporting", "Verdirrojo"],
  "Della Mea, Federico": ["Colon", "Larranaga", "Marne", "Montevideo", "Tabare"],
  "Demichelli, Jose": ["Ateneo", "Nacional", "Reducto", "Sayago", "Tabare"],
  "Desirello, Gonzalo": ["Paysandu", "Touring"],
  "Di Domenico, Alejandro": ["Stockolmo"],
  "Diaz Gavranic, Gonzalo": ["Malvin"],
  "Diaz Grecco, Nicolas": ["Montevideo", "Urupan"],
  "Diaz, Agustin": ["Welcome"],
  "Diaz, Fabian": ["Stockolmo"],
  "Diaz, Gonzalo": ["Malvin", "Tabare"],
  "Diaz, Jose": ["Marne", "Stockolmo"],
  "Diaz, Martin": ["Auriblanco"],
  "Diaz, Maximiliano": ["Albatros"],
  "Diez, Ignacio": ["Bigua"],
  "Digenio, Stefano": ["Union Atletica"],
  "Dogliotti, Mateo": ["Sayago"],
  "Dominguez, Fabio": ["Hebraica Macabi", "Plaza De Nueva Helvecia"],
  "Dominguez, Mauro": ["Hebraica Macabi"],
  "Donegana, Juan": ["Stockolmo"],
  "Dos Santos, Agustin": ["Larre Borges"],
  "Ducase, Juan": ["Trouviille"],
  "Dudoy, Martin": ["Defensor Sporting", "Independiente", "Olimpia", "Praga", "Yale"],
  "Dudoy, Sebastian": ["Independiente", "Malvin", "Praga"],
  "Dufrechou, Marcel": ["Juventud"],
  "Dumpierrez, Nicolas": ["Union Atletica"],
  "Elhordoy, Enrique": ["25 De Agosto", "Aguada", "Atenas", "Bohemios", "Hebraica Macabi", "Lagomar", "Larranaga", "Malvin", "Plaza", "Sayago", "Stockolmo", "Trouviille", "Union Atletica", "Verdirrojo"],
  "Elicegui, Francisco": ["25 De Agosto", "Anastasia", "Nacional De Fraybentos", "Trouviille"],
  "Ellis, Mauricio": ["Atenas", "Defensor Sporting", "Olivol Mundial", "Urunday Universitario"],
  "Ellis, Nicolas": ["Albatros"],
  "Ellis, Ramiro": ["Juventud", "Olimpia"],
  "Errico, Pablo": ["Yale"],
  "Escapa, Alejandro": ["Aguada", "Cordon", "Welcome"],
  "Escudero, Juan": ["Ateneo", "Nacional"],
  "Espindola, Agustin": ["Ferro Carril", "Malvin"],
  "Espindola, Gianfranco": ["Bohemios"],
  "Espinoza, Edison": ["Aguada", "Bohemios"],
  "Etcheverry, Nicolas": ["Albatros", "Miramar", "San Telmo", "Welcome", "Yale"],
  "FAROPPA, Angel": ["Olimpia", "Urunday Universitario"],
  "Fajardo, Pablo": ["Albatros", "Stockolmo", "Welcome", "Yale"],
  "Falero, Pablo": ["Aguada"],
  "Fallabrino, Federico": ["Ateneo", "Larranaga", "Larre Borges", "Stockolmo", "Union Atletica", "Urunday Universitario"],
  "Faluotico, Pablo": ["Remeros", "Stockolmo", "Urunday Universitario", "Yale"],
  "Fedrou, Agustin": ["Tabare"],
  "Fernandez Brasil, Jose": ["Aguada", "Marne", "Nacional", "Urunday Universitario"],
  "Fernandez, Darwin": ["Ateneo", "Larranaga", "Larre Borges", "Stockolmo", "Union Atletica", "Urunday Universitario"],
  "Fernandez, Fabian": ["Yale"],
  "Fernandez, Federico": ["Aguada"],
  "Fernandez, Gerardo": ["Guruyu Waston", "Marne", "Olimpia", "Sayago", "Stockolmo"],
  "Fernandez, Guido": ["Cader", "Colon", "Goes", "Marne", "Nacional", "San Telmo"],
  "Fernandez, Ignacio": ["Verdirrojo"],
  "Fernandez, Jose": ["Atenas", "Montevideo"],
  "Fernandez, Juan": ["Anastasia", "Larre Borges", "Marne", "Urunday Universitario", "Verdirrojo"],
  "Fernandez, Matias": ["Aguada", "San Telmo"],
  "Fernandez, Rodrigo": ["Bigua"],
  "Ferrari, Bruno": ["Aguada"],
  "Ferrari, Sebastian": ["Atenas"],
  "Ferreira, Ariel": ["Atenas", "Colon", "Hebraica Macabi", "Independiente", "Olimpia", "Remeros", "Soriano", "Stockolmo", "Union Atletica", "Yale"],
  "Ferreira, Fernando": ["Aguada", "San Telmo"],
  "Ferreira, Gonzalo": ["Remeros", "Stockolmo"],
  "Ferreira, Guido": ["Aguada", "Auriblanco", "Miramar", "Soriano", "Urunday Universitario", "Welcome"],
  "Ferreira, Marcelo": ["Marne", "Miramar", "Paysandu"],
  "Ferres, Andres": ["Trouviille"],
  "Ferrin, Juan Pablo": ["Larranaga", "San Telmo"],
  "Ferro, Fernando": ["Lagomar", "Union Atletica"],
  "Figueiredo, Carlos": ["Colon", "Olivol Mundial"],
  "Finozzi, Gabriel": ["Salto Uruguay"],
  "Firpo, Nicolas": ["Colon", "Malvin"],
  "Fittipaldo, Bruno": ["25 De Agosto", "Malvin"],
  "Flores, Matias": ["Verdirrojo"],
  "Folena, Facundo": ["Trouviille"],
  "Fontan, Jio": ["Bohemios"],
  "Fontes, Agustin": ["Urunday Universitario"],
  "Forcade, Ignacio": ["Auriblanco", "Verdirrojo"],
  "Franchetti, Esteban": ["Cordon"],
  "Franzozi, Ignacio": ["Malvin", "Yale"],
  "Freira, Santiago": ["Yale"],
  "Frigio, Mariano": ["Miramar", "Urunday Universitario"],
  "Frontan, Joaquin": ["Praga", "Soriano"],
  "Frugoni, Diego": ["Aguada", "Bigua", "Nacional", "Sayago"],
  "Frutos, Andres": ["Albatros", "Auriblanco", "Reducto"],
  "Frutos, Marcelo": ["25 De Agosto", "Ateneo"],
  "Fuentes, Gonzalo": ["Cordon"],
  "Fuentes, Santiago": ["Lagomar"],
  "GONZALEZ, Nicolas": ["Cader", "Union Atletica"],
  "Gabin, Andres": ["Tabare", "Urupan"],
  "Gadnich, Ignacio": ["Defensor Sporting"],
  "Gago, Jose": ["Bohemios"],
  "Galego, Nahuel": ["Urunday Universitario"],
  "Galleto, Juan Andres": ["Hebraica Macabi"],
  "Gallo Besio, Pablo": ["Romis Nelimar", "Sayago"],
  "Gallo, Ariel": ["Olivol Mundial"],
  "Gallo, Matias": ["Anastasia"],
  "Gallo, Mauricio": ["Goes", "Sayago"],
  "Galvan, Gervasio": ["Larre Borges", "Las Bovedas"],
  "Galvan, Victor": ["Larre Borges", "Las Bovedas", "San Telmo", "Urupan"],
  "Gamon, Leandro": ["Cader", "Juventud", "Sayago"],
  "Garay, Martin": ["Aguada", "Reducto"],
  "Garbarino, Juan": ["25 De Agosto", "Anastasia", "Bohemios", "Olimpia", "Olivol Mundial", "Sayago", "Tabare", "Trouviille", "Urunday Universitario"],
  "Garcia Morales, Leandro": ["Aguada", "Bigua", "Hebraica Macabi", "Larre Borges", "Olimpia"],
  "Garcia, Claudio": ["Ateneo", "Goes", "Marne", "Miramar", "Olivol Mundial", "Paysandu", "Tabare"],
  "Garcia, Diego": ["Aguada", "Atenas", "Defensor Sporting", "Verdirrojo"],
  "Garcia, Esteban": ["25 De Agosto", "Bohemios", "Stockolmo"],
  "Garcia, Francisco": ["Larranaga"],
  "Garcia, Gonzalo": ["Tabare"],
  "Garcia, Nicolas": ["Colon", "Lagomar", "Nacional", "Union Atletica"],
  "Garcia, Pablo": ["25 De Agosto", "Aguada", "Anastasia", "Cordon", "Guruyu Waston", "Hebraica Macabi", "Welcome"],
  "Gares, Daniel": ["Cader", "Miramar", "Olimpia", "Olivol Mundial"],
  "Gargallo, Ezequiel": ["Montevideo"],
  "Garland, Pablo": ["Plaza"],
  "Garriga, Alvaro": ["Juventud", "Yale"],
  "Gasanol, Matias": ["25 De Agosto", "Cader", "Marne", "Olimpia", "Racing", "Yale"],
  "Gastanaga, Felipe": ["Auriblanco", "Plaza De Nueva Helvecia", "Tabare"],
  "Gauna, Carlos": ["Anastasia", "Olivol Mundial", "Praga"],
  "Geller, Marcos": ["Bigua"],
  "Gelos, Jose": ["Hebraica Macabi", "Nacional"],
  "Gentini, Nicolas": ["Auriblanco", "Olivol Mundial", "Praga", "San Telmo", "Stockolmo", "Verdirrojo", "Waston"],
  "Geraldo, Agustin": ["Sayago"],
  "Gervasini, Carlos": ["Marne", "Verdirrojo"],
  "Gestal, Santiago": ["25 De Agosto"],
  "Ghans, Alvaro": ["Aguada", "Urupan"],
  "Giacometti, Mattia": ["Salto Uruguay"],
  "Giacometti, Renzo": ["Circulo Sportivo", "Nacional", "Olivol Mundial", "Salto Uruguay"],
  "Giano, Emiliano": ["Bigua", "Cordon", "Defensor Sporting", "Ferro Carril", "Malvin", "Nacional", "Sayago", "Touring", "Union Atletica", "Welcome"],
  "Gilardi, Marcio": ["25 De Agosto", "Cordon", "Montevideo"],
  "Giles, Fernando": ["Goes", "Marne"],
  "Gimenez, Geronimo": ["Olimpia"],
  "Girbau, Tadeo": ["Hebraica Macabi", "Olivol Mundial"],
  "Giz, Javier": ["Bohemios"],
  "Gobba, Sebastian": ["Cordon", "Welcome"],
  "Godoy, Rodolfo": ["Colon", "Larre Borges", "Marne", "Nacional", "Olivol Mundial", "Reducto", "Welcome", "Yale"],
  "Gomez, Gabriel": ["Cader"],
  "Gomez, Jair": ["Welcome"],
  "Gomez, Juan Ignacio": ["Bigua", "Nacional", "Romis Nelimar", "Tabare", "Welcome"],
  "Gomez, Rodrigo": ["Union Atletica"],
  "Gonzalez Aguirre, Sebastian": ["Aguada", "Circulo Sportivo", "Hebraica Macabi", "Independiente"],
  "Gonzalez Cabrera, Marcelo": ["Olivol Mundial"],
  "Gonzalez Espino, Sebastian": ["Lagomar"],
  "Gonzalez Fernandez, Rodrigo": ["25 De Agosto"],
  "Gonzalez Munoz, Marcelo": ["Miramar"],
  "Gonzalez, Andres": ["Defensor Sporting"],
  "Gonzalez, Diago": ["Nacional"],
  "Gonzalez, Diego": ["Circulo Sportivo", "Nacional", "Olivol Mundial", "Salto Uruguay"],
  "Gonzalez, Emiliano": ["25 De Agosto", "Cordon", "Goes", "Hebraica Macabi", "Montevideo", "Olimpia", "Racing", "Remeros", "Sayago", "Tabare"],
  "Gonzalez, Ignacio": ["25 De Agosto", "Larre Borges", "Las Bovedas", "Nacional", "Salto Uruguay", "Waston"],
  "Gonzalez, Juan Gabriel": ["Yale"],
  "Gonzalez, Rodrigo": ["Olimpia"],
  "Gonzalvo, Gonzalo": ["Urunday Universitario"],
  "Gordienko, Juan": ["Paysandu", "Touring"],
  "Gordillo, Nicolas": ["Cordon", "Romis Nelimar"],
  "Goyen, Gabriel": ["Olivol Mundial"],
  "Goyeneche, Fernando": ["San Telmo"],
  "Goyeneche, Mauricio": ["Malvin", "Marne", "Reducto"],
  "Grana, Diego": ["Defensor Sporting", "Tabare"],
  "Granger, Jason": ["Cordon"],
  "Greising, Nicolas": ["Plaza De Nueva Helvecia"],
  "Grolero, Rodolfo": ["Paysandu", "Touring"],
  "Grolla, Facundo": ["Bigua", "Stockolmo"],
  "Gruzdas, Andres": ["25 De Agosto", "Colon", "Miramar", "Olivol Mundial", "San Telmo", "Stockolmo", "Yale"],
  "Guerra, Emiliano": ["Ferro Carril"],
  "Guerra, Juan": ["Albatros", "Atenas", "Bigua", "Goes", "Romis Nelimar", "San Telmo", "Welcome"],
  "Guerra, Lucas": ["Defensor Sporting"],
  "Guerra, Matias": ["Cader", "Defensor Sporting", "Goes", "Guruyu Waston", "Verdirrojo", "Welcome"],
  "Guillen, Andres": ["Larre Borges"],
  "Gutierrez, Fernando": ["Nacional", "Paysandu", "Plaza De Nueva Helvecia", "Touring"],
  "Haller, Emanuele": ["Hebraica Macabi", "Plaza De Nueva Helvecia"],
  "Hammer, Friddi": ["Aguada", "Bohemios", "Cordon", "Defensor Sporting", "Independiente", "Nacional"],
  "Hellman, Facundo": ["Olimpia"],
  "Herasimechuck, Alexis": ["Goes", "Larranaga", "Miramar"],
  "Hernandez, Diego": ["Malvin"],
  "Hernandez, Esteban": ["Verdirrojo"],
  "Hernandez, Facundo": ["Trouviille"],
  "Hernandez, Matias": ["25 De Agosto"],
  "Holms, Philip": ["25 De Agosto"],
  "Hornos, Augusto": ["25 De Agosto", "Cader", "Larre Borges", "Olivol Mundial", "Paysandu", "Romis Nelimar", "Trouviille", "Yale"],
  "Hornos, Paul": ["Reducto"],
  "Horvat, Stefan": ["25 De Agosto", "Goes", "Independiente"],
  "Hourcade, Marcos": ["Bohemios", "Montevideo", "Olivol Mundial"],
  "Ibarra, Martin": ["Defensor Sporting"],
  "Ibarra, Nicolas": ["Anastasia", "Ateneo", "Bohemios", "Colon", "Cordon", "Goes", "Independiente", "Racing", "Remeros", "Sayago", "Soriano"],
  "Ibon,Pablo": ["25 De Agosto", "Colon", "Cordon", "Racing"],
  "Iglesia, Fernando": ["Atenas", "Tabare"],
  "Iglesias, Agustin": ["Goes", "Malvin", "Marne", "Montevideo", "Reducto", "Stockolmo", "Urunday Universitario", "Yale"],
  "Iglesias, Gonzalo": ["Aguada"],
  "Ijes, Nicolas": ["Marne"],
  "Illaramendi, Jan": ["Tabare"],
  "Insausti, Ernesto": ["Marne"],
  "Insua, Sntiago": ["Montevideo"],
  "Inthamoussu, Victor": ["Atenas", "Malvin", "Tabare"],
  "Introini, Luis": ["Albatros", "Miramar", "San Telmo", "Welcome"],
  "Invernizzi, Camilo": ["Hebraica Macabi"],
  "Iribarren, Alejandro": ["Aguada", "Ferro Carril", "Larranaga"],
  "Irureta, Javier": ["Welcome"],
  "Izaguirre, Sebastian": ["Bohemios", "Defensor Sporting", "Hebraica Macabi", "Larranaga", "Paysandu", "Touring", "Trouviille", "Union Atletica"],
  "Izaguirre,. Rodrigo": ["Cader"],
  "Izaurralde, Facundo": ["Larre Borges"],
  "Izuibejeres, Joaquin": ["Bohemios", "Goes", "Hebraica Macabi", "Larre Borges", "Malvin", "Trouviille"],
  "Izuibejeres, Matias": ["25 De Agosto", "Sayago", "Trouviille"],
  "Jennings, Timothy": ["Aguada", "Bigua", "Cordon", "Larre Borges", "Plaza De Nueva Helvecia", "Romis Nelimar", "Tabare", "Verdirrojo"],
  "Jones, Andres": ["Albatros", "Auriblanco", "Hebraica Macabi", "Larranaga", "Olivol Mundial"],
  "Jones, Joaquin": ["Auriblanco", "Bigua"],
  "Jones, Michael": ["Aguada", "Bigua", "Cordon", "Larre Borges", "Plaza De Nueva Helvecia", "Romis Nelimar", "Tabare", "Verdirrojo"],
  "Jorcin, Leonardo": ["Independiente"],
  "Juan, Nicolas": ["Plaza", "Urunday Universitario"],
  "Juarez, Federico": ["Union Atletica"],
  "Jubin, Alejandro": ["Ateneo", "Circulo Sportivo", "Paysandu", "Sayago", "Welcome"],
  "Kalemkerian, Matias": ["Tabare"],
  "Kanis, Brad": ["Trouviille", "Welcome"],
  "Kanovich, Sebastian": ["Bigua"],
  "Klisich, Santiago": ["Cader"],
  "Laborda, Adrian": ["Aguada", "Goes", "Hebraica Macabi", "Lagomar", "Malvin", "Remeros", "Salto Uruguay", "Tabare", "Union Atletica"],
  "Lacues, Ismael": ["Larranaga"],
  "Lado, Matias": ["Goes", "Sayago", "Stockolmo", "Trouviille", "Welcome"],
  "Laduche, Gaston": ["Larre Borges"],
  "Lagomarsino, Bruno": ["Larre Borges", "Marne", "Miramar"],
  "Lambert, Abel": ["Larre Borges", "Paysandu", "Stockolmo", "Urupan"],
  "Lambert, Eduardo": ["Independiente", "Marne", "Plaza", "Praga", "Stockolmo", "Urunday Universitario", "Verdirrojo"],
  "Lapaz, Hugo": ["Praga", "Soriano"],
  "Laplazotte, Jorge": ["Larre Borges"],
  "Larre, Francisco": ["Aguada", "Anastasia", "Atenas", "Cader", "Cordon", "Larre Borges", "Las Bovedas", "Marne", "Nacional De Fraybentos", "Paysandu"],
  "Larrea, Gonzalo": ["Lagomar"],
  "Lasarga, Martin": ["Defensor Sporting", "Malvin", "Paysandu", "Tabare", "Urunday Universitario"],
  "Laubert, Pablo": ["Anastasia", "Praga"],
  "Lazzaroni, Renzo": ["Anastasia", "Cordon", "Goes", "Independiente", "Larre Borges", "Montevideo", "Olimpia", "Sayago", "Stockolmo"],
  "Ledanis, Alejandro": ["Larranaga"],
  "Leguizamon, Sebastian": ["Nacional", "Olimpia", "Plaza De Nueva Helvecia", "Remeros", "Urunday Universitario"],
  "Leiva, Franco": ["Marne"],
  "Lema, Gabriel": ["Goes", "Olivol Mundial", "Stockolmo"],
  "Lema, Matias": ["Plaza De Nueva Helvecia"],
  "Leon, Santiago": ["Larranaga", "Trouviille"],
  "Lespada, Diego": ["Bohemios", "Goes", "Nacional", "Stockolmo", "Waston", "Yale"],
  "Lewin, Salomon": ["Colon"],
  "Lewis, Nicolas": ["Miramar", "Nacional", "Tabare"],
  "Lima, Atilio": ["Salto Uruguay", "Stockolmo"],
  "Lipatin, Daniel": ["25 De Agosto", "Bigua", "Colon"],
  "Lopez Cardozo, Andres": ["Defensor Sporting"],
  "Lopez Garcia, Rodrigo": ["Tabare"],
  "Lopez, Alex": ["Bigua", "Larre Borges", "Marne", "Sayago", "Stockolmo", "Trouviille"],
  "Lopez, Claudio": ["Larre Borges"],
  "Lopez, Damian": ["25 De Agosto", "Cader", "Guruyu Waston", "Malvin", "Olivol Mundial", "Stockolmo"],
  "Lopez, Diego": ["Tabare"],
  "Lopez, Eduardo": ["Plaza De Nueva Helvecia"],
  "Lopez, German": ["Paysandu"],
  "Lopez, Joan Andoni": ["25 De Agosto"],
  "Lopez, Juan": ["Romis Nelimar", "Tabare"],
  "Lopez, Leonardo": ["Aguada"],
  "Lopez, Martin": ["Colon", "Hebraica Macabi", "Miramar", "Plaza De Nueva Helvecia", "Remeros", "Soriano", "Verdirrojo"],
  "Lopez, Nunez, Mauricio": ["Defensor Sporting", "Olivol Mundial"],
  "Lopez, Rodrigo": ["Defensor Sporting", "Goes", "Nacional", "Waston"],
  "Lopez, Sebastian": ["Miramar"],
  "Lopez, Valentin": ["Anastasia"],
  "Lorenzo, Matias": ["Auriblanco", "Verdirrojo"],
  "Loriente, Ivan": ["Atenas", "Bigua", "Goes", "Olimpia", "Tabare", "Welcome"],
  "Lotitto, Leonardo": ["Hebraica Macabi", "Urupan"],
  "Lozano, Fernando": ["25 De Agosto", "Ateneo", "Colon", "Lagomar", "Olivol Mundial", "Reducto", "Yale"],
  "Luhers, Martin": ["Independiente", "Soriano", "Waston"],
  "Luzuriaga, Valentin": ["Circulo Sportivo", "Welcome"],
  "MACHADO, Agustin": ["Cader"],
  "MORALES, Carlos": ["Nacional"],
  "Macanskas, Pablo": ["Olimpia"],
  "Macchi, Luca": ["Olimpia"],
  "Machado, Christian": ["Larre Borges"],
  "Machado, Leonardo": ["Lagomar"],
  "Machado, Santiago": ["Urunday Universitario"],
  "Maggiari, Andres": ["Yale"],
  "Maglione, Claudio": ["Independiente"],
  "Magnone, Juan Bautista": ["Nacional", "Remeros", "Trouviille"],
  "Magnone, Luca": ["Aguada", "Cordon", "Stockolmo"],
  "Magurno, Diego": ["Yale"],
  "Mainentti, Mauro": ["Ateneo", "Bohemios", "Colon", "Union Atletica"],
  "Maiochi, Agustin": ["Hebraica Macabi", "Plaza"],
  "Mancebo, Sergio": ["Goes", "Larranaga", "Yale"],
  "Manicera, Marcelo": ["Hebraica Macabi", "Nacional", "Sayago", "Urunday Universitario", "Waston"],
  "Manzini Magli, Marco": ["Hebraica Macabi", "Paysandu", "Tabare"],
  "Marchelli, Carlos": ["Yale"],
  "Marchelli, Ricardo": ["San Telmo", "Yale"],
  "Marenales, Martin": ["Nacional"],
  "Mariani, Bruno": ["Colon", "Stockolmo"],
  "Marichal, Alfredo": ["Welcome"],
  "Marichal, Matias": ["Paysandu", "Reducto", "Tabare", "Trouviille", "Union Atletica", "Waston", "Welcome"],
  "Marino, Rodrigo": ["Albatros", "Ateneo", "Olivol Mundial", "Stockolmo"],
  "Marotta, Marcos": ["Bohemios", "Goes", "Independiente", "Larre Borges", "Montevideo", "Trouviille", "Welcome"],
  "Marquisa, Facundo": ["Larranaga", "Malvin"],
  "Marr, Christian": ["Olivol Mundial"],
  "Martinez, Guzman": ["Larranaga"],
  "Martinez Nacere, Diego": ["Trouviille"],
  "Martinez Vinoly, Matias": ["Atenas", "Goes", "Union Atletica"],
  "Martinez, Agustin": ["25 De Agosto", "Urunday Universitario"],
  "Martinez, Andres": ["Trouviille"],
  "Martinez, Diego": ["Goes", "Nacional"],
  "Martinez, Diego Andres": ["Larranaga"],
  "Martinez, Federico": ["Aguada", "Bohemios", "Cordon", "Defensor Sporting", "Hebraica Macabi", "Larranaga", "Marne", "Sayago", "Soriano", "Trouviille", "Union Atletica", "Urunday Universitario", "Welcome"],
  "Martinez, Gustavo": ["Bohemios", "Goes", "Larre Borges", "Olivol Mundial", "Sayago", "Trouviille"],
  "Martinez, Hernan": ["Lagomar"],
  "Martinez, Horacio": ["Anastasia", "Cordon", "Malvin", "Olimpia", "Paysandu", "Soriano"],
  "Martinez, Ignacio": ["Colon", "Urunday Universitario"],
  "Martinez, Ivan": ["Nacional"],
  "Martinez, Mauricio": ["Larre Borges"],
  "Martinez, Maximiliano": ["Albatros"],
  "Martinez, Oscar": ["Anastasia", "Remeros"],
  "Martinez, Osvaldo": ["Atenas", "Defensor Sporting", "Malvin", "Nacional", "Plaza", "Sayago", "Urunday Universitario", "Welcome"],
  "Martinez, Raul": ["Ateneo", "Olivol Mundial"],
  "Martinez, Rodrigo": ["Reducto", "Stockolmo"],
  "Martinez, Roney": ["Aguada", "Bigua", "Independiente", "Malvin", "Salto Uruguay", "Sayago", "Soriano"],
  "Martinez, Sebastian": ["25 De Agosto", "Guruyu Waston", "Larranaga", "Marne", "Miramar", "Racing", "Verdirrojo"],
  "Martinez,Tabare": ["25 De Agosto", "Anastasia", "Ateneo", "Bohemios", "Larranaga", "Malvin", "Marne", "Montevideo", "Nacional", "Olivol Mundial", "Plaza", "Reducto", "Sayago", "Yale"],
  "Masaferro, Gaston": ["Marne", "Urunday Universitario"],
  "Masaferro, Lucas": ["Reducto"],
  "Masner, Federico": ["Miramar", "Yale"],
  "Massa, Santiago": ["Bigua", "Hebraica Macabi", "Trouviille", "Verdirrojo"],
  "Mateu, Pedro": ["Cordon", "Nacional", "Reducto", "Waston"],
  "Matienzo, Richard": ["Atenas", "Circulo Sportivo", "Nacional", "Paysandu", "Union Atletica"],
  "Matoso, Mauricio": ["Cader", "Malvin", "Romis Nelimar", "Yale"],
  "Maturana, Sebastian": ["Cordon"],
  "Maurno, Nicolas": ["Bigua"],
  "May, Nicolas": ["25 De Agosto", "Atenas", "Tabare"],
  "Mayora, Juan Manuel": ["25 De Agosto", "Montevideo", "Trouviille"],
  "Mayora, Martin": ["Larre Borges", "Marne", "San Telmo", "Trouviille"],
  "Mazzarino, Nicolas": ["Hebraica Macabi", "Malvin", "Welcome"],
  "Mazzuchi, Cristian": ["Union Atletica"],
  "Mazzuco, Federico": ["Cordon", "Larre Borges"],
  "Medina, Octavio": ["Hebraica Macabi", "Stockolmo", "Tabare"],
  "Meira, Gonzalo": ["Bigua", "Goes", "Montevideo", "Nacional", "Tabare", "Welcome"],
  "Melgarejo, Rodrigo": ["Olimpia"],
  "Mendana, Santiago": ["Plaza De Nueva Helvecia", "Stockolmo"],
  "Mendez, Maximiliano": ["Atenas", "Trouviille"],
  "Mendia, Ignacio": ["Welcome"],
  "Mendilaharzu, Maximiliano": ["Aguada"],
  "Menendez, Liber": ["Guruyu Waston", "Hebraica Macabi", "Larre Borges"],
  "Merelo, Elias": ["Anastasia"],
  "Midaglia, Alvaro": ["Goes"],
  "Miglionico, Julio": ["Aguada", "Bigua", "Larre Borges", "Sayago", "Yale"],
  "Miller, Federico": ["Urunday Universitario"],
  "Minervini, Diego": ["Verdirrojo"],
  "Miraglia, Alvaro": ["Goes"],
  "Miramontes, Esteban": ["Las Bovedas", "Romis Nelimar", "Sayago"],
  "Miranda, Mauro": ["Nacional"],
  "Modernell, Juan": ["Goes", "Guruyu Waston", "Larre Borges", "Nacional", "Nacional De Fraybentos", "Union Atletica", "Verdirrojo"],
  "Modernell, Maximiliano": ["Miramar"],
  "Moglia, Santiago": ["Anastasia", "Bigua", "Larranaga", "Larre Borges", "Nacional", "Union Atletica", "Welcome"],
  "Monetti, Maurizio": ["Romis Nelimar", "Salto Uruguay", "Tabare"],
  "Monico, Mauro": ["Aguada"],
  "Monroe, Tarrie": ["Bohemios", "Cader", "Larre Borges", "Romis Nelimar", "Sayago", "Union Atletica", "Yale"],
  "Montemurro, German": ["Larre Borges", "San Telmo", "Welcome"],
  "Montemurro, Gustavo": ["Atenas", "Cader", "Malvin", "Nacional", "Reducto"],
  "Monterroso, Ignacio": ["Cader", "Malvin", "Reducto"],
  "Monterroso, Santiago": ["25 De Agosto", "Larranaga", "Malvin", "Nacional", "Welcome"],
  "Monterroso,. Julio": ["Romis Nelimar"],
  "Monteverde, Felipe": ["Trouviille"],
  "Monteverde, Manuel": ["Larre Borges", "Trouviille", "Verdirrojo"],
  "Morales, Alexis": ["Olimpia"],
  "Morales, Pablo": ["Aguada", "Cordon", "Hebraica Macabi", "Malvin", "Nacional", "Paysandu", "Salto Uruguay", "Trouviille", "Urunday Universitario"],
  "Morales, Sebastian": ["Verdirrojo"],
  "Morena, Andres": ["Malvin"],
  "Morencos, Ignacio": ["Trouviille"],
  "Moreno, Maximiliano": ["Stockolmo"],
  "Muela, Claudio": ["Guruyu Waston", "Olivol Mundial"],
  "Muguiro, Diego": ["Auriblanco", "Cordon"],
  "Muniz, Jorge": ["Larre Borges", "Las Bovedas"],
  "Muniz, Jose": ["Cordon"],
  "Munoz, Martin": ["25 De Agosto", "Colon", "Defensor Sporting", "Nacional", "Plaza De Nueva Helvecia", "Urupan"],
  "Munoz, Sebastian": ["25 De Agosto", "Atenas", "Ateneo", "Bohemios", "Cordon", "Defensor Sporting", "Malvin", "Olivol Mundial", "Paysandu", "Tabare", "Touring", "Urunday Universitario", "Verdirrojo"],
  "Mussio, Maximiliano": ["Albatros"],
  "Nalerio, Agustin": ["Olivol Mundial"],
  "Narbais, Fabian": ["Atenas", "Hebraica Macabi", "Juventud", "Las Bovedas", "Montevideo", "Olivol Mundial", "Plaza", "Verdirrojo"],
  "Nathan, Guillermo": ["Bigua", "Larre Borges", "Montevideo", "Urunday Universitario", "Yale"],
  "Navarrete, Freddy": ["Goes", "Welcome"],
  "Navarrine, Mauro": ["Larranaga"],
  "Nessi, Marcelo": ["Defensor Sporting", "Miramar", "Montevideo"],
  "Nicoletti, Matias": ["Larre Borges", "Miramar", "Stockolmo"],
  "Nieves, Josuel": ["Bohemios", "Miramar", "San Telmo"],
  "Niquichenco, Gerardo": ["25 De Agosto", "Bigua", "Cordon", "Defensor Sporting", "Goes", "Malvin", "Olimpia", "Romis Nelimar", "Sayago", "Tabare", "Trouviille", "Urunday Universitario", "Verdirrojo", "Welcome"],
  "Niquichenco, Gustavo": ["Reducto"],
  "Nobile, Maximiliano": ["Olimpia"],
  "Noe, Santiago": ["Miramar", "Paysandu", "Verdirrojo", "Yale"],
  "Nogueira, Alexis": ["Anastasia", "Nacional De Fraybentos"],
  "Nuevo, Raul": ["Plaza"],
  "Nunez, Nicolas": ["Reducto"],
  "Oholeguy, Matias": ["25 De Agosto", "Ateneo", "Bigua", "Lagomar"],
  "Ojeda, Nicolas": ["Verdirrojo"],
  "Olejnik, Luis": ["Aguada", "Atenas", "Marne", "Nacional", "Paysandu", "Welcome"],
  "Olivera, Diego": ["Atenas", "Independiente", "Olivol Mundial", "Sayago", "Tabare", "Welcome"],
  "Olivera, Franco": ["Larre Borges"],
  "Olivera, Nicolas": ["Praga", "Soriano"],
  "Olivera, Rodrigo": ["Ateneo", "Bohemios", "Urunday Universitario"],
  "Olivera, Ruben": ["Atenas", "Larranaga", "Yale"],
  "Onetto, Ismael": ["Larranaga"],
  "Opperti, Sebastian": ["Sayago"],
  "Ordono, Fernando": ["Independiente", "Racing", "Soriano"],
  "Ormando, Renzo": ["Sayago"],
  "Ormechea, Joaquin": ["Cader"],
  "Ortega del Rio, Joaquin": ["Bigua", "Defensor Sporting"],
  "Ortega del Rio, Juan Manuel": ["Defensor Sporting"],
  "Ortiz, Ignacio": ["25 De Agosto", "Bigua", "Cader"],
  "Osimani, Joaquin": ["Bigua"],
  "Osimani, Martin": ["Bigua"],
  "Osores, Schubert": ["Anastasia"],
  "Otatti, Edgardo": ["Anastasia"],
  "Otonello, Marcos": ["Urunday Universitario"],
  "Ottonello, Sebastian": ["25 De Agosto", "Welcome"],
  "Oviedo, David": ["Welcome"],
  "Owens, Trelonnie": ["Bigua", "Welcome"],
  "Oxandabarat, German": ["Atenas", "Defensor Sporting", "Hebraica Macabi", "Las Bovedas", "Nacional", "Verdirrojo"],
  "PASSOS, Hatila de Souza": ["Atenas", "Hebraica Macabi", "Malvin"],
  "Pacheco, Gustavo": ["Ateneo"],
  "Pacilio, Alvaro": ["Atenas"],
  "Paez, Gonzalo": ["Juventud"],
  "Pagani, Gianni": ["Cader"],
  "Palacios, Fabrizio": ["Albatros"],
  "Palarino, Lucas": ["Cader", "Olivol Mundial"],
  "Palavecino, Washington": ["Marne", "Stockolmo"],
  "Pancic, Juan": ["Trouviille"],
  "Panelli, Julio": ["Auriblanco", "Bohemios", "Cader", "Ferro Carril", "Marne", "Olivol Mundial", "Urunday Universitario"],
  "Panowski, Joaquin": ["Bohemios"],
  "Paolillo, Federico": ["Anastasia", "Goes", "Olivol Mundial", "Soriano", "Yale"],
  "Papariello, Tabare": ["Atenas", "Cordon", "Goes", "Larre Borges"],
  "Paradiso, Mathias": ["Reducto"],
  "Pardo, Adrian": ["Olivol Mundial"],
  "Paredes, Alfredo": ["Aguada", "Stockolmo"],
  "Parodi, Luciano": ["Hebraica Macabi"],
  "Parodi, Ruben": ["Auriblanco"],
  "Parra, Mauricio": ["Cordon"],
  "Parreno, Mauricio": ["Verdirrojo"],
  "Pasini, Gonzalo": ["Miramar"],
  "Pasqualli, Federico": ["Ateneo", "Bohemios", "Cordon", "Lagomar", "Marne", "Reducto"],
  "Pastorino, Sebastian": ["Anastasia", "Bohemios", "Cordon", "Larranaga", "Montevideo", "Olivol Mundial"],
  "Pastrana, Ciro": ["Goes", "Larre Borges", "Waston"],
  "Pau, Julian": ["Ateneo", "Independiente", "Plaza De Nueva Helvecia", "Stockolmo"],
  "Pavon, Agustin0": ["25 De Agosto"],
  "Penna, Martin": ["Trouviille", "Union Atletica", "Welcome"],
  "Pepe, Nicolas": ["Aguada", "Ateneo", "Bigua", "Paysandu", "Trouviille", "Yale"],
  "Peralta, Matias": ["Paysandu"],
  "Peralta, Pablo": ["Olimpia"],
  "Perdomo, Martin": ["Bohemios", "Sayago", "Union Atletica"],
  "Pereira das Neves, Gustavo": ["Larre Borges"],
  "Pereira, Cristian": ["Goes", "Marne", "Nacional De Fraybentos"],
  "Pereira, Dario": ["Sayago"],
  "Pereira, Federico": ["Aguada", "Bigua", "Montevideo"],
  "Pereira, Martin": ["Aguada", "Cordon"],
  "Pereira, Nicolas": ["Cordon"],
  "Pereira, Pablo": ["Larranaga", "Urupan"],
  "Perera, Guzman": ["Union Atletica"],
  "Pereyra, Diego": ["Bohemios", "Paysandu"],
  "Pereyra, Javier": ["Cader"],
  "Pereyra, Luis": ["Juventud"],
  "Perez, Alejandro": ["Aguada", "Atenas", "Bohemios", "Hebraica Macabi", "Montevideo", "Nacional", "Sayago", "Trouviille", "Union Atletica", "Welcome"],
  "Perez, Diego": ["Cordon", "Goes", "Malvin", "Nacional", "Urunday Universitario", "Welcome", "Yale"],
  "Perez, Fabian": ["Montevideo", "Welcome"],
  "Perez, Ignacio": ["San Telmo", "Yale"],
  "Perez, Julian": ["Verdirrojo"],
  "Perez, Lautaro": ["Racing"],
  "Perez, Marcelo": ["Atenas", "Bigua", "Bohemios", "Larranaga", "Malvin", "Nacional", "Sayago", "Trouviille", "Welcome", "Yale"],
  "Perez, Mateo": ["Urunday Universitario"],
  "Perez, Nicolas": ["Olivol Mundial"],
  "Perez, Rodrigo": ["Cordon", "Larre Borges", "Tabare", "Waston"],
  "Perona, Mateo": ["Malvin"],
  "Pessano, Daniel": ["Bohemios", "Lagomar"],
  "Picasso, Federico": ["Bohemios"],
  "Piedrabuena, Ariel": ["Larranaga", "Miramar"],
  "Pierri, Luis": ["Bohemios"],
  "Pineiro, Andres": ["25 De Agosto", "Auriblanco", "Cader", "Marne", "Olimpia", "Verdirrojo", "Yale"],
  "Pineiro, Ezequiel": ["Goes"],
  "Pineiro, Joaquin": ["Trouviille"],
  "Pintos, Leandro": ["25 De Agosto", "Anastasia", "Colon", "Lagomar", "Miramar", "Montevideo", "Olivol Mundial", "Praga", "Reducto", "Sayago", "Trouviille", "Waston", "Welcome", "Yale"],
  "Pintos, Rodrigo": ["Cordon", "Hebraica Macabi", "Stockolmo"],
  "Piriz, Gabriel": ["Verdirrojo"],
  "Pita, Hernan": ["Montevideo", "Sayago", "Trouviille"],
  "Pizzani, Diego": ["Larranaga"],
  "Pizzini, Nicolas": ["Larranaga", "Union Atletica"],
  "Planells, Luciano": ["Atenas"],
  "Polvarini, Luciano": ["25 De Agosto", "Colon", "Cordon", "Romis Nelimar", "Tabare"],
  "Polvarini, Mauro": ["Bigua", "Romis Nelimar", "Tabare", "Union Atletica"],
  "Pomoli, Fausto": ["Atenas", "Larranaga", "Malvin", "Montevideo"],
  "Pongibove, Bruno": ["Tabare"],
  "Pons, Ignacio": ["25 De Agosto", "Anastasia", "Atenas", "Ferro Carril", "Goes", "Larranaga", "Larre Borges", "Miramar", "Montevideo", "Reducto", "Stockolmo", "Union Atletica", "Waston", "Yale"],
  "Pons, Juan": ["Anastasia", "Sayago", "Stockolmo"],
  "Ponte, Mauricio": ["Independiente", "Soriano"],
  "Porfilio, Agustin": ["Atenas"],
  "Posada, Enrique": ["Larranaga", "Nacional", "Trouviille", "Union Atletica"],
  "Pose, Mateo": ["Atenas"],
  "Posse, Agustin": ["Atenas"],
  "Pozzolo, Ignacio": ["Montevideo"],
  "Prato, Diego": ["Cader", "Olimpia", "Verdirrojo"],
  "Prego, Francisco": ["Albatros", "Urunday Universitario"],
  "Premazzi, Diego": ["Malvin"],
  "Premuda, Fernando": ["Ateneo"],
  "Previatti, Rafael": ["Malvin"],
  "Puig, Guillermo": ["Cordon", "Marne", "Olivol Mundial"],
  "Puyol, Ruben": ["Anastasia", "Nacional De Fraybentos"],
  "Quijano, Gonzalo": ["Waston"],
  "Quinteros, Enrique": ["Colon", "Goes", "Olivol Mundial", "Tabare", "Yale"],
  "Quiroga, Martin": ["Nacional"],
  "ROBAINA, Gabriel": ["Auriblanco", "Olivol Mundial", "Verdirrojo"],
  "Rafaelli, Daniel": ["Goes", "Miramar", "Stockolmo", "Urunday Universitario"],
  "Raggioto, Mathias": ["Welcome"],
  "Rak, Pablo": ["Bigua", "Bohemios", "Cader", "Cordon", "Defensor Sporting", "Olimpia", "Olivol Mundial", "Trouviille"],
  "Rama, Federico": ["Bohemios", "Marne", "Yale"],
  "Ramirez, Alvaro": ["Bohemios", "Defensor Sporting", "Las Bovedas", "Marne", "Sayago", "Waston"],
  "Ramirez, Santiago": ["Larre Borges", "Malvin", "Marne", "Montevideo", "Tabare"],
  "Rava, Renzo": ["Hebraica Macabi", "Larre Borges", "Olivol Mundial", "Reducto", "Romis Nelimar", "Urunday Universitario"],
  "Realan, Marcelo": ["Atenas"],
  "Refresquines, Luis": ["Bigua"],
  "Regalado, Juan Martin": ["Marne", "Paysandu", "Tabare"],
  "Reig, Gustavo": ["Goes"],
  "Reina, Fabian": ["Hebraica Macabi", "Larranaga", "Malvin", "Racing", "Tabare"],
  "Ressi, Matias": ["Cader", "Larre Borges", "Sayago", "Welcome"],
  "Retamoso, Joaquin": ["Tabare"],
  "Rey, Agustin": ["Bohemios", "San Telmo"],
  "Rey, Santiago": ["Stockolmo"],
  "Reyes, Manuel": ["Defensor Sporting", "Paysandu"],
  "Reyes, Pablo": ["Paysandu"],
  "Reymondez, Adrian": ["Ferro Carril", "Plaza De Nueva Helvecia", "Tabare", "Trouviille", "Union Atletica", "Yale"],
  "Riba, Sebastian": ["25 De Agosto"],
  "Riera, Rodrigo": ["Aguada", "Cader", "Cordon", "Defensor Sporting", "Malvin", "Nacional", "Trouviille", "Union Atletica"],
  "Riezler, Nicolas": ["Bigua", "Tabare"],
  "Risso, Matias": ["Olimpia", "Stockolmo"],
  "Rivas, Gonzalo": ["Tabare", "Urunday Universitario", "Welcome"],
  "Rivas, Matias": ["Larre Borges", "Miramar", "Nacional"],
  "Riveiro, Camilo": ["Malvin", "Plaza", "Sayago"],
  "Rivera, Juliano": ["Aguada", "Hebraica Macabi", "Malvin", "Salto Uruguay", "Tabare", "Trouviille", "Welcome"],
  "Rivero, Daniel": ["25 De Agosto", "Aguada", "Atenas", "Bohemios", "Cader", "Defensor Sporting", "Larranaga", "Malvin", "Montevideo", "Nacional", "Olimpia", "Sayago", "Stockolmo", "Trouviille", "Welcome", "Yale"],
  "Rivero, Rodrigo": ["Auriblanco", "Olivol Mundial", "Verdirrojo"],
  "Rivero, Sergio": ["Yale"],
  "Robaina, Mathias": ["Aguada"],
  "Rocha, Pablo0": ["Goes", "Olivol Mundial"],
  "Rocha, Santiago": ["Welcome"],
  "Rodriguez Delfino, Santiago": ["Larre Borges", "Malvin"],
  "Rodriguez Freitas, Santiago": ["Colon", "Montevideo", "Olivol Mundial"],
  "Rodriguez Olivera, Juan Manuel": ["Lagomar", "Tabare"],
  "Rodriguez Santana, Horacio": ["Bigua", "Bohemios"],
  "Rodriguez, Alex": ["Atenas", "Cordon", "Defensor Sporting", "Goes", "Juventud", "Plaza", "Tabare"],
  "Rodriguez, Andres": ["Colon", "Reducto"],
  "Rodriguez, Dionisio": ["Stockolmo"],
  "Rodriguez, Emilio": ["Montevideo"],
  "Rodriguez, Enzo": ["Union Atletica"],
  "Rodriguez, Johnny": ["Anastasia", "Atenas", "Bohemios", "Cordon", "Defensor Sporting", "Goes", "Independiente", "Larre Borges", "Nacional", "Remeros", "Romis Nelimar", "Tabare", "Union Atletica", "Welcome", "Yale"],
  "Rodriguez, Juan": ["Welcome"],
  "Rodriguez, Juan Pedro": ["Remeros"],
  "Rodriguez, Lucas": ["Aguada", "Verdirrojo"],
  "Rodriguez, Mateo": ["Reducto"],
  "Rodriguez, Matias": ["Montevideo"],
  "Rodriguez, Pablo": ["Cader", "Union Atletica"],
  "Rodriguez, Pedro": ["Reducto", "Romis Nelimar", "Tabare"],
  "Rodriguez, Ramiro": ["Olivol Mundial", "Remeros"],
  "Rodriguez, Santiago": ["Tabare"],
  "Rodriguez, Yannick": ["Tabare"],
  "Rojas, Martin": ["Bigua"],
  "Roman, Gonzalo": ["Stockolmo"],
  "Romero, Diego": ["Goes", "Welcome"],
  "Romero, Gaston": ["Aguada", "Cader"],
  "Romero, Gustavo": ["Colon", "Cordon", "Independiente", "Larre Borges", "Las Bovedas", "Nacional", "Olivol Mundial", "Verdirrojo"],
  "Rompani, Bruno": ["Colon", "Malvin", "Romis Nelimar"],
  "Ronco, Federico": ["Miramar", "Romis Nelimar", "Tabare"],
  "Rondeau, Luis": ["Marne", "Miramar"],
  "Roselli, Facundo": ["Anastasia", "Bigua", "Cader", "Hebraica Macabi", "Marne", "Nacional", "Yale"],
  "Roses, Marcelo": ["Sayago"],
  "Rosmarino, Nicolas": ["25 De Agosto", "Colon", "Larre Borges", "Tabare"],
  "Rostan, Jesus": ["Cordon", "Defensor Sporting", "Malvin", "Nacional", "Plaza", "Waston"],
  "Rovira, Juan": ["Aguada", "Bigua", "Nacional", "Tabare"],
  "Rusch, Pierino": ["Hebraica Macabi"],
  "SAAVEDRA, Agustin": ["Guruyu Waston"],
  "Salas, Santiago": ["Olivol Mundial"],
  "Saldanha, Victor": ["25 De Agosto", "Atenas", "Auriblanco", "Cader", "Montevideo", "Olivol Mundial", "Romis Nelimar", "Tabare", "Urunday Universitario", "Verdirrojo"],
  "Salvia, Roberto": ["Colon", "Stockolmo", "Yale"],
  "San Miguel, Andres": ["Anastasia", "Bigua", "Defensor Sporting", "Nacional", "Olimpia", "Sayago", "Yale"],
  "Sanchez, Facundo": ["Atenas", "Auriblanco", "Cader", "Olivol Mundial", "Romis Nelimar", "Urunday Universitario"],
  "Sanchez, Federico": ["Cordon", "Nacional", "Yale"],
  "Sanchez, Gabriel": ["Atenas", "Juventud", "Olimpia"],
  "Sanchez, Marcelo": ["Plaza", "Urunday Universitario"],
  "Santos, Nahuel": ["Aguada", "Union Atletica"],
  "Santos, Nahuel0": ["Aguada"],
  "Saravia, Mathias": ["Goes", "Marne", "Olivol Mundial"],
  "Saucedo, Jorge": ["Atenas", "Nacional", "Plaza De Nueva Helvecia", "Praga", "Soriano", "Tabare", "Verdirrojo"],
  "Saudaskas, Alvaro": ["Cordon", "Stockolmo"],
  "Scarpenti, Ignacio": ["Olivol Mundial"],
  "Schneck, Kevin": ["Cordon"],
  "Seguessa, Federico": ["Auriblanco", "Olivol Mundial"],
  "Sellanes, Carlos": ["Hebraica Macabi", "Olivol Mundial"],
  "Serqui, Carlos": ["Anastasia"],
  "Serres, Emiliano": ["Malvin", "Tabare"],
  "Sgorlo, Anibal": ["Hebraica Macabi", "Juventud", "Lagomar", "Stockolmo", "Yale"],
  "Shamlian, Daniel": ["Juventud", "Verdirrojo"],
  "Shaw, Sebastian": ["Trouviille"],
  "Shellman, Terence": ["Nacional", "Sayago", "Tabare"],
  "Sienra, Mauricio": ["Atenas"],
  "Sierra, Fernando": ["Malvin", "Plaza De Nueva Helvecia", "Stockolmo", "Waston"],
  "Sierra, Hugo": ["Bohemios", "Nacional", "Plaza", "Racing", "Salto Uruguay", "Union Atletica"],
  "Silva, Brian": ["Urunday Universitario"],
  "Silva, Fernando": ["Olimpia"],
  "Silva, Gaston": ["San Telmo"],
  "Silva, Hector": ["Olivol Mundial", "Romis Nelimar", "Sayago", "Verdirrojo"],
  "Silva, Jonatan": ["25 De Agosto", "Auriblanco", "Hebraica Macabi", "Lagomar", "Larre Borges", "Marne", "Montevideo", "Olivol Mundial"],
  "Silva, Jorge Tabare": ["25 De Agosto", "Hebraica Macabi", "Lagomar", "Larre Borges", "Marne"],
  "Silvarrey, German": ["Malvin", "Olimpia", "Olivol Mundial", "Sayago", "Urunday Universitario", "Verdirrojo", "Welcome"],
  "Silveira, Diego": ["25 De Agosto", "Cader", "Goes", "Nacional", "Reducto", "San Telmo"],
  "Silveira, Jonathan": ["Atenas"],
  "Silveira, Juan Pablo": ["25 De Agosto", "Defensor Sporting", "Hebraica Macabi", "Olimpia", "Salto Uruguay", "Trouviille", "Union Atletica"],
  "Silveira, Luis": ["Defensor Sporting", "Sayago", "Stockolmo", "Welcome"],
  "Siniestro, Facundo": ["Cader"],
  "Siniscalchi, Pierino": ["Reducto", "Romis Nelimar", "Welcome"],
  "Skirzewski, Erik": ["Olivol Mundial"],
  "Somma, Mauro": ["Colon", "Malvin"],
  "Sonderegger, Florian": ["25 De Agosto", "Plaza De Nueva Helvecia"],
  "Soria, Daniel": ["Anastasia", "Nacional De Fraybentos"],
  "Soria, Fernando": ["Colon", "Malvin"],
  "Soria, Guillermo": ["Auriblanco", "Larranaga", "Las Bovedas", "Marne", "Miramar", "Montevideo", "Plaza", "Reducto", "Yale"],
  "Sosa Rodriguez, Alvaro": ["Touring"],
  "Sosa, Alvaro": ["Soriano"],
  "Sosa, Leandro": ["Miramar"],
  "Sosa, Matias": ["Goes"],
  "Sosa, Sebastian": ["Goes"],
  "Souto, Guillermo": ["Colon", "Plaza De Nueva Helvecia", "San Telmo"],
  "Sparano, Andres": ["Juventud", "Stockolmo"],
  "Speranza, Marcelo": ["Bigua", "Plaza De Nueva Helvecia", "Verdirrojo"],
  "Suarez, Cristian": ["Larre Borges"],
  "Suarez, Emiliano": ["25 De Agosto", "Atenas", "Auriblanco", "Larranaga", "Montevideo", "Sayago"],
  "Suarez, Mario": ["Bohemios", "Montevideo"],
  "Suarez, Martin": ["Atenas", "Bigua", "Cader", "Cordon", "Independiente", "Malvin", "Nacional", "Trouviille", "Union Atletica"],
  "Suarez, Mateo": ["Montevideo", "Urunday Universitario"],
  "Suarez, Mauricio": ["Lagomar"],
  "Suarez, Mauro": ["Montevideo"],
  "Szczygielsi Merla, Gustavo": ["Malvin"],
  "Szczygielski, Gustavo": ["Bigua", "Defensor Sporting", "Hebraica Macabi", "Welcome"],
  "Taboada, Leandro": ["Aguada", "Bohemios", "Hebraica Macabi", "Lagomar", "Larre Borges", "Malvin", "Montevideo", "Nacional", "Soriano", "Urunday Universitario", "Yale"],
  "Teperino, Ruben": ["Olivol Mundial"],
  "Terra, Facundo": ["Bohemios", "Urunday Universitario"],
  "Texeira, Diego": ["Urunday Universitario"],
  "Tiago, Roberto": ["Union Atletica"],
  "Till, Andres": ["Atenas", "Larranaga", "Miramar", "Montevideo", "Paysandu", "Touring"],
  "Till, Daniel": ["Larranaga", "Paysandu", "Touring"],
  "Timote, Hugo": ["Aguada", "Anastasia", "Bohemios", "Defensor Sporting", "Ferro Carril", "Guruyu Waston", "Larre Borges", "Montevideo", "Nacional De Fraybentos", "Remeros", "Tabare", "Union Atletica", "Urunday Universitario"],
  "Tinte, Nicolas": ["Atenas"],
  "Tissierre, Cristian": ["Colon", "Guruyu Waston", "Malvin", "Nacional", "Yale"],
  "Tolmero, Leandro": ["Plaza De Nueva Helvecia", "San Telmo"],
  "Tolosa, Santiago": ["Cader", "Defensor Sporting", "Larre Borges"],
  "Tome, Manuel": ["Defensor Sporting", "Miramar"],
  "Tornaria, German": ["Olimpia", "Yale"],
  "Torrens, Alvaro": ["Miramar"],
  "Torres, Joaquin": ["Juventud", "Sayago"],
  "Tortajada, Diego": ["Bohemios", "Union Atletica", "Urunday Universitario"],
  "Trapote, Danny": ["Anastasia", "Bigua", "Bohemios", "Ferro Carril", "Independiente", "Nacional", "Trouviille"],
  "Trasante, Mauricio": ["Aguada", "Cordon", "Larre Borges", "Nacional", "Olimpia", "Plaza", "Plaza De Nueva Helvecia", "Trouviille"],
  "Trelles, Martin": ["Bohemios", "Miramar", "Sayago"],
  "Trindade,  Jorge": ["25 De Agosto", "Aguada", "Atenas", "Hebraica Macabi", "Urunday Universitario", "Verdirrojo"],
  "Trinidad, Rodrigo": ["Marne"],
  "Triver, Gaston": ["Aguada", "Cordon", "Larre Borges", "Nacional", "Olimpia", "Plaza", "Plaza De Nueva Helvecia", "Trouviille"],
  "Trombotti, Juan": ["Yale"],
  "Trusich, Felipe": ["Marne", "Union Atletica"],
  "Tucuna, Enrique": ["Aguada", "Bigua", "Bohemios", "Cordon", "Hebraica Macabi", "Malvin", "Union Atletica", "Welcome"],
  "Ubal, Agustin": ["Malvin"],
  "Vacca, Leonardo": ["Bohemios", "Cader", "Cordon", "Hebraica Macabi", "Nacional", "Olimpia", "Plaza", "Salto Uruguay", "Tabare", "Union Atletica"],
  "Varela, Angel": ["Defensor Sporting", "Larre Borges", "Olimpia", "Olivol Mundial", "Plaza", "Union Atletica", "Urunday Universitario", "Welcome", "Yale"],
  "Varela, Emiliano": ["Union Atletica"],
  "Varela, German": ["Bigua", "Union Atletica"],
  "Varela, Matias": ["Tabare"],
  "Vargas, Christian": ["Verdirrojo"],
  "Vargas, Damian": ["25 De Agosto"],
  "Vargas, Gaston": ["Larre Borges", "Miramar", "Paysandu"],
  "Varini, Federico": ["Olivol Mundial", "Trouviille"],
  "Vasallo, Gaspar": ["Larre Borges"],
  "Vasquez, Manuel": ["Nacional"],
  "Vassallucci, Lucas": ["25 De Agosto", "Aguada", "Malvin"],
  "Vazquez, Alberto": ["25 De Agosto", "Atenas", "Cordon", "Larranaga"],
  "Vazquez, Carlos": ["Albatros", "Yale"],
  "Vazquez, Hugo": ["Aguada", "Bigua", "Bohemios", "Defensor Sporting", "Welcome"],
  "Vazquez, Maximiliano": ["Stockolmo"],
  "Vazquez, Mike": ["Lagomar"],
  "Vazquez, Santiago": ["Bohemios", "Nacional"],
  "Vazquez, Sebastian": ["Anastasia", "Bohemios", "Larranaga", "Olimpia", "Tabare", "Welcome"],
  "Veigas, Bruno": ["Goes"],
  "Veleda, Dario": ["Sayago", "Verdirrojo", "Yale"],
  "Venditto, Matias": ["Marne", "Olimpia", "Olivol Mundial"],
  "Vera, Diego": ["Praga", "Soriano"],
  "Vera, Facundo": ["Plaza", "Plaza De Nueva Helvecia"],
  "Verlo, Ramiro": ["Anastasia", "Paysandu"],
  "Verocay, Maximiliano": ["Ferro Carril"],
  "Verrone, Fernando": ["25 De Agosto", "Aguada", "Cader", "Goes", "Larre Borges", "Stockolmo", "Welcome"],
  "Vescovi, Santiago": ["Bohemios"],
  "Viana, Juan": ["Olimpia", "Stockolmo"],
  "Vidal, Juan Jose": ["Cordon", "Tabare"],
  "Vidal, Santiago": ["Aguada", "Bigua", "Larranaga", "Larre Borges", "Nacional", "Tabare", "Trouviille"],
  "Viera, Pablo": ["Anastasia", "Atenas", "Hebraica Macabi", "Malvin", "Montevideo", "Olimpia", "Paysandu", "Trouviille"],
  "Vietro, Facundo": ["Salto Uruguay"],
  "Vignart, Ricardo": ["Goes", "Malvin"],
  "Vignoli, Joaquin": ["Malvin", "Sayago"],
  "Villafane, Nicolas": ["Colon"],
  "Villamarzo, Tomas": ["Bohemios"],
  "Villareal, Mauricio": ["Verdirrojo"],
  "Villoldo, Sebastian": ["Reducto", "Tabare", "Urunday Universitario"],
  "Vincent, Ivan": ["Miramar", "Yale"],
  "Viotti, Agustin": ["Cordon", "Hebraica Macabi"],
  "Vique,  Esteban": ["Larranaga", "Paysandu", "Urupan"],
  "Vispo, Juan Jose": ["Trouviille"],
  "Volf, Martin": ["Larranaga", "Paysandu", "Urupan"],
  "Wachsmann, Kiril": ["Defensor Sporting", "Hebraica Macabi"],
  "Wenzel, Juan": ["25 De Agosto", "Praga", "Romis Nelimar", "Trouviille"],
  "Williams, Anthony": ["Atenas", "Circulo Sportivo", "Independiente", "Nacional", "Soriano", "Trouviille"],
  "Yaquinta, Nicolas": ["Atenas", "Sayago"],
  "Yeghyaian Casartelli, Daniel": ["25 De Agosto"],
  "Yeniselli, Kevin": ["Larranaga"],
  "Yern, Adrian": ["Atenas", "Cordon", "Larranaga", "Marne", "Verdirrojo"],
  "Yona, Pedro": ["Miramar"],
  "Yozzi, Agustin": ["Yale"],
  "Zaballa, Juan Carlos": ["Anastasia", "Atenas", "Bohemios", "Cordon", "Defensor Sporting", "Larranaga", "Larre Borges", "Malvin", "Nacional", "Sayago", "Tabare", "Urunday Universitario", "Urupan", "Welcome"],
  "Zachow, Julian": ["Hebraica Macabi"],
  "Zannier, Facundo": ["Olivol Mundial"],
  "Zanotta, Salvador": ["Cordon", "Hebraica Macabi", "Nacional"],
  "Zarrillo, Diego": ["Miramar", "San Telmo", "Welcome"],
  "Zavala, Ignacio": ["Albatros", "Olivol Mundial", "Verdirrojo"],
  "Zavala, Santiago": ["Trouviille"],
  "Zeballos, Leandro": ["Colon"],
  "Zoryez, Sergio": ["Bohemios", "Cordon", "Hebraica Macabi", "Independiente", "Las Bovedas", "Nacional", "Olivol Mundial", "Plaza", "Waston"],
  "Zubiaurre, Mario": ["Atenas", "Cordon", "Marne", "Urunday Universitario"],
  "Zubich, Agustin": ["Cordon", "Hebraica Macabi", "Nacional"],
  "Zuibruck, Daniel": ["Cordon"],
};
